---
apiVersion: v1
kind: Namespace
metadata:
  name: uat
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: goldeploy
  namespace: uat
  labels:
    app: golsvc
  annotations:
    kubernetes.io/change-cause: "version 1.2"
spec:
  replicas: 3
  selector:
    matchLabels:
      app: golsvc
  template:
    metadata:
      labels:
        app: golsvc
        version: v1.2
    spec:
      containers:
        - image: rajanikanthraju/gol_fea:v1.0
          name: golsvc
          ports:
            - containerPort: 8080
      imagePullSecrets:
        - name: docregcred        
---
apiVersion: v1
kind: Service
metadata:
  name: gol-svc
  namespace: uat
  labels:
    job: nodeport
spec:
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30001
      protocol: TCP
  selector:
    app: golsvc
  type: NodePort
